# -*- coding: utf-8 -*-
"""Bank_personal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zzqjorCyOvnoBKP24m78Uq4FDFYcsWMA
"""

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

df = pd.read_csv("Bank_Personal_Loan_Modelling.csv")

df.head()

df.isnull().sum()

df.info()

df.nunique()

df.drop(["ID","ZIP Code"],axis=1,inplace = True)

df.head()

df.columns

df.Education.nunique()

int_cols = ['Age', 'Experience', 'Income', 'Family', 'CCAvg','Mortgage']

cat_cols = ['Education', 'Personal Loan', 'Securities Account', 'CD Account','Online', 'CreditCard']

df[int_cols] = df[int_cols].astype(int)

df[cat_cols] = df[cat_cols].astype("category")

df.info()

X = df.drop(['Personal Loan'],axis = 1)

X.columns

y = df['Personal Loan']

from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X, y)

import pickle
pickle.dump(regressor, open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))

